CREATE TABLE STATS (
STAT_ID INT(11) auto_increment PRIMARY KEY,
STAT_DATE DATETIME NOT NULL,
STAT VARCHAR(20) NOT NULL,
VALUE INT(11) NOT NULL
);




CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*)
FROM READERS RD, BOOKS BK, RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;


SELECT * FROM books_and_readers
WHERE RENT_DATE >= CURDATE() - 5
ORDER BY FIRSTNAME;



UPDATE READERS 
SET VIP_LEVEL = "NOT SET"
WHERE READER_ID IN (1,2,3,4,5);

COMMIT; 

SELECT * FROM READERS;