CREATE TABLE STATS (
STAT_ID INT(11) auto_increment PRIMARY KEY,
STAT_DATE DATETIME NOT NULL,
STAT VARCHAR(20) NOT NULL,
VALUE INT(11) NOT NULL
);

select * from stats;


CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*)
FROM BOOKS
WHERE BESTSELLER = 1;

SHOW PROCESSLIST;

SET GLOBAL EVENT_SCHEDULER=ON;




UPDATE READERS 
SET VIP_LEVEL = "NOT SET"
WHERE READER_ID IN (1,2,3,4,5);

COMMIT; 

SELECT * FROM READERS;