CREATE TABLE BOOKS_AUD (
	EVENT_ID INT(11) NOT NULL auto_increment,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    BOOK_ID INT(11) NOT NULL,
    OLD_TITLE VARCHAR(255),
    NEW_TITLE VARCHAR(255),
    OLD_PUBYEAR VARCHAR(4),
    NEW_PUBYEAR VARCHAR(4),
	OLD_BESTSELLER BOOLEAN,
    NEW_BESTSELLER BOOLEAN,
    PRIMARY KEY(`EVENT_ID`)
);

SELECT * FROM kodilla_course.books_aud;

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN 
	insert into BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER)
			VALUES (CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER);
END $$

DELIMITER ;

INSERT INTO BOOKS (TITLE, PUBYEAR, BESTSELLER)
		VALUES ("PAN TADEUSZ", 1799, TRUE);
        
COMMIT;


DELIMITER $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN 
	insert into BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
			VALUES (CURTIME(), "DELETE", OLD.BOOK_ID);
END $$

DELIMITER ;

DELETE FROM BOOKS WHERE BOOK_ID = 4;

COMMIT;


DELIMITER $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN 
	insert into BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER,
							OLD_TITLE, OLD_PUBYEAR, OLD_BESTSELLER)
			VALUES (CURTIME(), "UPDATE", OLD.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER,
							OLD.TITLE, OLD.PUBYEAR, OLD.BESTSELLER);
END $$

DELIMITER ;

UPDATE  BOOKS SET PUBYEAR = 1935
WHERE BOOK_ID = 2;

UPDATE  BOOKS SET 
TITLE = "BOOK OF ELI",
BESTSELLER = FALSE
WHERE BOOK_ID = 2;

COMMIT;