SELECT * FROM READERS;
SELECT * FROM books;

CREATE INDEX BOOKSINDX ON BOOKS (TITLE);
CREATE INDEX READERSIDNX ON READERS (FIRSTNAME, LASTNAME);

EXPLAIN SELECT COUNT(*)
FROM READERS 
WHERE FIRSTNAME = "JOHN";
