SHOW PROCESSLIST;

USE KODILLA_COURSE;

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) as HOW_MANY
FROM BOOKS
WHERE BESTSELLER = 1;

INSERT INTO STATS (VALUE) 
	SELECT COUNT(*) AS HOW_MANY
	FROM BESTSELLERS_COUNT;

DELIMITER $$

CREATE EVENT UPDATE_STATS
ON SCHEDULE EVERY 15 second
DO 	
BEGIN

    INSERT INTO STATS (STAT_DATE, STAT,VALUE) 
	VALUES (curdate(),"BESTSELLERS", (SELECT HOW_MANY FROM  BESTSELLERS_COUNT));
    
    CALL UpdateBestSellers();
    
END $$

DELIMITER ;
COMMIT;

SELECT * FROM STATS;